sudo: required
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.8.2

before_install:
  - docker pull bryanlatten/docker-php:latest
  - docker pull bryanlatten/docker-php:9.2-legacy
  - docker-compose build seven
  - docker-compose build fivesix

script:
  - docker-compose run seven
  - docker-compose run fivesix
