sudo: false
language: php
php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5
  - 5.4

before_script: phpenv config-add .travis.php.ini

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

install:
  - composer install
